/** @type {import('tailwindcss').Config} */
export default {
  darkMode: ["class"],
  content: [
    "./index.html",
    "./src/**/*.{ts,tsx,js,jsx}",
  ],
  theme: {
    extend: {
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "#c0c1ff",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "#a4c9ff",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        "primary-container": "#8083ff",
        "cyan-flare": "#06B6D4",
        "surface-container": "#191f31",
        "tertiary-container": "#b76dff",
        "outline-variant": "#464554",
        "inverse-primary": "#494bd6",
        "surface-tint": "#c0c1ff",
        "surface-container-high": "var(--surface-container-high)",
        "slate-text": "var(--slate-text)",
        "surface": "var(--surface)",
        "secondary-container": "#0267b8",
        "on-tertiary-container": "#400071",
        "on-secondary": "#00315d",
        "on-surface": "var(--on-surface)",
        "secondary-fixed": "#d4e3ff",
        "surface-container-lowest": "#070d1f",
        "on-primary-container": "#0d0096",
        "outline": "#908fa0",
        "secondary-fixed-dim": "#a4c9ff",
        "error": "#ffb4ab",
        "on-secondary-container": "#d6e5ff",
        "surface-container-highest": "var(--surface-container-highest)",
        "electric-indigo": "#6366F1",
        "surface-variant": "#2e3447",
        "tertiary-fixed-dim": "#ddb7ff",
        "surface-bright": "#33394c",
        "on-secondary-fixed-variant": "#004883",
        "surface-dim": "#0c1324",
        "on-tertiary-fixed-variant": "#6900b3",
        "on-surface-variant": "#c7c4d7",
        "on-primary-fixed-variant": "#2f2ebe",
        "on-error-container": "#ffdad6",
        "inverse-surface": "#dce1fb",
        "tertiary": "#ddb7ff",
        "on-secondary-fixed": "#001c39",
        "primary-fixed-dim": "#c0c1ff",
        "inverse-on-surface": "#2a3043",
        "tertiary-fixed": "#f0dbff",
        "on-primary-fixed": "#07006c",
        "on-background": "#dce1fb",
        "on-error": "#690005",
        "obsidian-deep": "var(--obsidian-bg)",
        "vibrant-violet": "#A855F7",
        "error-container": "#93000a",
        "on-tertiary": "#490080",
        "on-primary": "#1000a9",
        "primary-fixed": "#e1e0ff",
        "on-tertiary-fixed": "#2c0051",
        "surface-container-low": "#151b2d"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "stack-md": "1.5rem",
        "margin-mobile": "1rem",
        "margin-desktop": "2.5rem",
        "gutter": "1.5rem",
        "container-max": "1440px",
        "stack-lg": "3rem",
        "stack-xs": "0.5rem"
      },
      fontFamily: {
        "body-md": ["Inter"],
        "body-lg": ["Inter"],
        "label-caps": ["Inter"],
        "headline-md": ["Plus Jakarta Sans"],
        "body-sm": ["Inter"],
        "headline-lg-mobile": ["Plus Jakarta Sans"],
        "headline-lg": ["Plus Jakarta Sans"],
        "display-lg": ["Plus Jakarta Sans"]
      },
      fontSize: {
        "body-md": ["16px", {"lineHeight": "24px", "fontWeight": "400"}],
        "body-lg": ["18px", {"lineHeight": "28px", "fontWeight": "400"}],
        "label-caps": ["12px", {"lineHeight": "16px", "letterSpacing": "0.05em", "fontWeight": "600"}],
        "headline-md": ["24px", {"lineHeight": "32px", "fontWeight": "600"}],
        "body-sm": ["14px", {"lineHeight": "20px", "fontWeight": "400"}],
        "headline-lg-mobile": ["24px", {"lineHeight": "32px", "fontWeight": "700"}],
        "headline-lg": ["32px", {"lineHeight": "40px", "letterSpacing": "-0.01em", "fontWeight": "700"}],
        "display-lg": ["48px", {"lineHeight": "56px", "letterSpacing": "-0.02em", "fontWeight": "800"}]
      }
    },
  },
  plugins: [
    require('@tailwindcss/typography'),
  ],
}
